"""Generate the Windows version resource for the frozen executable.

`dist\\ClipDock\\ClipDock.exe` reports an empty FileVersion, ProductName,
CompanyName and FileDescription, so Task Manager, file Properties and Windows'
installed-programs list all show nothing for it.  `ClipDock-Setup.exe` does carry
them, because Inno Setup writes a version resource of its own - which makes the
asymmetry worse, not better: the installer identifies itself and the program it
installs does not.

PyInstaller's `--version-file` closes that.  The resource has to be a file on
disk, and a file cannot import `__version__`, so the value is written here from
the one place it actually lives.  That is the whole point: a version literal
typed into a second file is exactly the defect this project has already paid for
twice - a stale FFmpeg User-Agent and a stale installer first page, both invisible
until somebody read them.  Generating instead of duplicating means a bump to
`__init__.py` is the only bump there is, and a test compares the two.

Only strings that are genuinely known are written.  `CompanyName` is left as the
product name rather than invented, and `InternalName` carries the module name so
Task Manager's Details tab shows something real rather than a blank row.

There is also a `--check` mode that writes nothing and exits non-zero if the file
on disk differs from what would be written, so a suite can verify a copy without
producing one.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Run as a script, this file's own directory is what lands on sys.path, not the
# repository root, so __version__ would not be importable.  Guarded because the
# test suite imports this module directly and would otherwise have the root
# inserted once per import.
_ROOT = str(Path(__file__).resolve().parents[1])
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from youtube_downloader import __version__

# PyInstaller's version resource format.  The numeric quadruple must be four
# integers, so a two-part version is padded with zeros; 0.2.0 becomes 0,2,0,0.
#
# The keyword names below are PyInstaller's own, not the longer spelling the
# hand-written version-file examples on the internet use.  This is not a
# cosmetic difference: FixedFileInfo.__init__ takes OS, fileType, subtype and
# date, so a file naming VOS_NT_WINDOWS32 or VFT_APP instead is rejected with
# "unexpected keyword argument", and the build fails.  They are read back from
# the installed PyInstaller rather than assumed, which is how the first draft of
# this file was caught - it had been written from memory and would have failed
# only at build time.
#
# OS is 0x40004, which is VOS_NT_WINDOWS32 combined with VOS_DOS_WINDOWS32, and
# is PyInstaller's own default for a 32-bit-capable Windows application.
# fileType 0x1 is VFT_APP, the only correct value for an .exe that is not a
# driver, font or DLL.
def _quadruple(version: str) -> tuple[int, int, int, int]:
    parts: list[int] = []
    for piece in version.split("."):
        digits = "".join(character for character in piece if character.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])


def render(product: str, version: str, description: str) -> str:
    major, minor, build, revision = _quadruple(version)
    return f"""# Generated by tools\\make_version_file.py - do not edit.
# Every value here comes from youtube_downloader\\__init__.py or the product name
# in scripts\\build_exe.ps1, so this file cannot name a version the program does
# not report.  See PROJECT_MAP.md for the two stale-version defects this
# approach exists to prevent.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {build}, {revision}),
    prodvers=({major}, {minor}, {build}, {revision}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{product}'),
         StringStruct(u'FileDescription', u'{description}'),
         StringStruct(u'FileVersion', u'{version}'),
         StringStruct(u'InternalName', u'{product}'),
         StringStruct(u'LegalCopyright', u''),
         StringStruct(u'OriginalFilename', u'{product}.exe'),
         StringStruct(u'ProductName', u'{product}'),
         StringStruct(u'ProductVersion', u'{version}')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument(
        "--product",
        default="ClipDock",
        help="product name; must match $appName in build_exe.ps1",
    )
    parser.add_argument(
        "--description",
        default="Desktop downloader for video, audio and subtitles",
        help="FileDescription shown in file Properties",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if the file on disk differs from what would be written",
    )
    arguments = parser.parse_args(argv)

    wanted = render(arguments.product, __version__, arguments.description)
    target: Path = arguments.output

    if arguments.check:
        if not target.is_file():
            print(f"missing: {target}", file=sys.stderr)
            return 1
        existing = target.read_text(encoding="utf-8-sig")
        if existing != wanted:
            print(
                f"stale: {target} does not match youtube_downloader.__version__ "
                f"({__version__})",
                file=sys.stderr,
            )
            return 1
        print(f"current: {target} names version {__version__}")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    # No BOM, and LF newlines.  PyInstaller evaluates the file's text, so a
    # leading U+FEFF is a syntax error rather than something it tolerates - and
    # `Out-File -Encoding utf8` on Windows PowerShell 5.1 emits exactly that.
    # The encoding and the newline are both named because Windows would
    # otherwise pick the locale codepage.
    #
    # Note this cannot be checked with ast.literal_eval, which is the obvious
    # thing to reach for: the file's top-level expression is a *call*,
    # `VSVersionInfo(...)`, and literal_eval rejects calls by design.  PyInstaller
    # evaluates it against its own namespace of stub classes.  So the only honest
    # check is PyInstaller's loader - see the test named for it.
    target.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"wrote {target} naming version {__version__}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())